##########################################################################
# Title:         Cloudbox: Plex | Default Variables                      #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Name
################################

plex_name: plex

################################
# Subdomain
################################

plex_subdomain: "{{ plex_name }}"

################################
# Folders
################################

plex_folder: "{{ plex_name }}"

plex_transcodes_path: "{{ transcodes_path }}/{{ plex_folder }}"

plex_path: "{{ server_appdata_path }}/{{ plex_folder }}"

plex_folders:
  - "{{ plex_path }}"
  - "{{ plex_path }}/Library"
  - "{{ plex_path }}/Library/Application Support"
  - "{{ plex_path }}/Library/Application Support/Plex Media Server"
  - "{{ plex_path }}/Library/Application Support/Plex Media Server/Plug-ins"
  - "{{ plex_path }}/Library/Logs"
  - "{{ plex_path }}/Library/Logs/Plex Media Server"
  - "{{ plex_transcodes_path }}"

################################
# Paths
################################

plex_application_support_path: "{{ plex_path }}/Library/Application Support/Plex Media Server"

plex_config_file_path: "{{ plex_application_support_path }}/Preferences.xml"

plex_log_path: "{{ plex_application_support_path }}/Logs"

plex_plugins_path: "{{ plex_application_support_path }}/Plug-ins"

plex_plugin_support_path: "{{ plex_application_support_path }}/Plug-in Support"

plex_db_path: "{{ plex_plugin_support_path }}/Databases/com.plexapp.plugins.library.db"

################################
# Docker Container
################################

plex_docker_container: "{{ plex_name }}"

################################
# Docker Image
################################

plex_docker_image: "plexinc/pms-docker:{{ plex.tag }}"

plex_docker_pull: yes

################################
# Docker Ports
################################

plex_main_ports:
  - "32400-32410:32400/tcp"

plex_extra_ports:
  - "3005:3005/tcp"
  - "8324:8324/tcp"
  - "32469:32469/tcp"
  - "1900:1900/udp"
  - "32410:32410/udp"
  - "32412:32412/udp"
  - "32413:32413/udp"
  - "32414:32414/udp"

webtools_ports:
  - "33400-33401:33400/tcp"
  - "33443-33453:33443/tcp"

# Port openings decision making

## Open main port(s) if enabled or reverse proxy is disabled
plex_open_main_ports: "{{ plex_main_ports
                          if plex.open_main_ports or
                              reverse_proxy_is_enabled
                          else [] }}"

## Open extra ports if enabled and for only one main plex container
plex_open_extra_ports: "{{ plex_extra_ports
                            if plex.open_extra_ports and
                                plex_name == 'plex'
                            else [] }}"

plex_docker_ports: "{{ plex_open_main_ports + plex_open_extra_ports + webtools_ports }}"

################################
# Docker Envs
################################

plex_web_port: 32400

plex_docker_envs_standard:
  PLEX_UID: "{{ uid }}"
  PLEX_GID: "{{ gid }}"
  PLEX_CLAIM: "{{ (plex_claim_code) | default(omit) }}"
  CHANGE_CONFIG_DIR_OWNERSHIP: "false"
  ADVERTISE_IP: "http://{{ ip_address_host }}:{{ plex_web_port }}/"
  HEALTHCHECK_MOUNT: /mnt/unionfs
  NVIDIA_DRIVER_CAPABILITIES: "{{ 'compute,video,utility' if (gpu.nvidia.enabled) | default(false) else omit }}"
  NVIDIA_VISIBLE_DEVICES: "{{ 'all' if (gpu.nvidia.enabled) | default(false) else omit }}"
  TZ: "{{ tz }}"

plex_docker_envs_reverse_proxy_extras:
  ADVERTISE_IP: "http://{{ plex_subdomain }}.{{ user.domain }}:80/,https://{{ plex_subdomain }}.{{ user.domain }}:443/"
  HTTPS_METHOD: noredirect

plex_docker_envs: "{{ (plex_docker_envs_standard |
                          combine(docker_envs_reverse_proxy) |
                          combine(plex_docker_envs_reverse_proxy_extras))
                      if (reverse_proxy_is_enabled)
                      else (plex_docker_envs_standard) }}"

################################
# Docker Volumes
################################

plex_docker_volumes:
  - "{{ plex_path }}:/config"
  - "{{ server_appdata_path }}/scripts:/scripts"
  - "/mnt/unionfs/Media:/data"
  - "/mnt:/mnt"
  - "/tmp:/tmp"
  - "/dev/shm:/dev/shm"
  - "{{ plex_transcodes_path }}:/transcode"

################################
# Docker Devices
################################

plex_docker_devices: []

################################
# Docker Hosts
################################

lazyman_ip: "{{ ( lookup('dig', 'powersports.ml', '@8.8.8.8', 'qtype=A') | ipv4 ) | default(false,true) }}"

plex_docker_hosts_custom:
  "metric.plex.tv": "{{ ip_address_localhost }}"
  "metrics.plex.tv": "{{ ip_address_localhost }}"
  "analytics.plex.tv": "{{ ip_address_localhost }}"
  "mf.svc.nhl.com": "{{ lazyman_ip | ternary(lazyman_ip, omit) }}"
  "mlb-ws-mf.media.mlb.com": "{{ lazyman_ip | ternary(lazyman_ip, omit) }}"
  "playback.svcs.mlb.com": "{{ lazyman_ip | ternary(lazyman_ip, omit) }}"

plex_docker_hosts: "{{ docker_hosts_common | combine(plex_docker_hosts_custom) }}"

################################
# Docker Labels
################################

plex_docker_labels:
    - '{ "traefik.http.services.{{ subdomain }}.loadbalancer.server.port": "{{ web_port }}" }'
    - "traefik.enable": "true"
    
docker_labels: "{{ docker_labels_common | combine(plex_docker_labels) }}"

################################
# Docker Hostname
################################

plex_docker_hostname: "{{ plex_name }}"

################################
# Docker Networks
################################

plex_docker_networks_alias: "{{ plex_name }}"

plex_docker_networks_custom: []

plex_docker_networks: "{{ docker_networks_common + plex_docker_networks_custom }}"

################################
# Docker Capabilities
################################

plex_docker_capabilities: []

################################
# Docker Security
################################

plex_docker_security_opts: []

################################
# Docker Restart Policy
################################

plex_docker_restart_policy: unless-stopped

################################
# Docker State
################################

plex_docker_state: started
