#########################################################################
# Title:         Cloudbox: UnionFS | Service Tasks                      #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Services | Check if '{{ _service_file }}' exists"
  stat:
    path: "/etc/systemd/system/{{ _service_file }}"
  register: _service_file_status

- name: "Services | Tasks for '{{ _service_file }}'"
  block:

  - name: "Services | Stop and disable existing '{{ _service_file }}'"
    systemd:
      name: "{{ _service_file }}"
      state: stopped
      enabled: no
    ignore_errors: yes

  - name: "Services | Update credentials in existing '{{ _service_file }}'"
    ini_file:
      path: "/etc/systemd/system/{{ _service_file }}"
      section: Service
      option: "{{ inner_item.option }}"
      value: "{{ inner_item.value }}"
      state: "{{ inner_item.state }}"
      no_extra_spaces: yes
    loop:
      - { option: 'User', value: '{{ user.name }}', state: "{{ 'absent' if (_service_file != 'mergerfs.service') else 'absent' }}" }
      - { option: 'Group', value: '{{ user.name }}', state: "{{ 'absent' if (_service_file != 'mergerfs.service') else 'absent' }}" }
    loop_control:
      loop_var: inner_item

  - name: "Services | Systemd daemon-reload"
    systemd: daemon_reload=yes

  when: _service_file_status.stat.exists
