#########################################################################
# Title:         Cloudbox: Tautulli | Legacy Migration Tasks            #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Legacy Migration | Cloudflare: Remove 'plexpy' subdomain from '{{ user.domain }}'"
  include_role:
    name: dns
  vars:
    record: plexpy
    action: remove

- name: Legacy Migration | Stop and remove 'plexpy' container
  docker_container:
    name: plexpy
    state: absent

# Migrate folder

- name: Legacy Migration | Check if new folder exists
  stat:
    path: "{{ tautulli_path }}"
  register: new_folder

- name: Legacy Migration | Check if legacy folder exists
  stat:
    path: "{{ server_appdata_path }}/plexpy"
  register: legacy_folder

- name: Legacy Migration | Move legacy folder to new folder if possible
  shell: |
    mv '{{ server_appdata_path }}/plexpy' '{{ tautulli_path }}'
    chown -R {{ user.name }}:{{ user.name }} '{{ tautulli_path }}'
  when: legacy_folder.stat.exists and not new_folder.stat.exists
