#########################################################################
# Title:         Cloudbox: Sonarr | Post-Install Tasks                  #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Update ports in preferences
- name: Post-Install | Check if '{{ sonarr_config_file_path | basename }}' exists
  stat:
    path: "{{ sonarr_config_file_path }}"
  register: sonarr_config_file_path_stat

- name: Post-Install | Update '{{ sonarr_config_file_path | basename }}'
  block:

  - name: Post-Install | Get host port that's mapped to docker port '8989'
    shell:
      docker port {{ sonarr_docker_container }} 8989 | sed 's/[0-9.]*://'
    register: sonarr_docker_port_8989
    changed_when: no

  - name: Post-Install | Set 'sonarr_docker_port_8989' variable
    set_fact:
      sonarr_docker_port_8989: >-
        {{ sonarr_docker_port_8989.stdout | trim 
            if sonarr_docker_port_8989.stdout | trim | length > 0
            else '8989' }}

  - name: Post-Install | Update 'Port' in '{{ sonarr_config_file_path | basename }}'
    xml:
      path: "{{ sonarr_config_file_path }}"
      xpath: /Config/Port
      value: "{{ sonarr_docker_port_8989 }}"
      state: present
    become: yes
    become_user: "{{ user.name }}"
    ignore_errors: yes

  when: sonarr_config_file_path_stat.stat.exists
