####################################################################################
# Title:         Cloudbox: Resources | Tasks | Nginx-Proxy | Create htpasswd       #
# Author(s):     desimaniac                                                        #
# URL:           https://github.com/cloudbox/cloudbox                              #
# --                                                                               #
#         Part of the Cloudbox project: https://cloudbox.works                     #
####################################################################################
#                   GNU General Public License v3.0                                #
####################################################################################
---
- name: Resources | Tasks | Nginx-Proxy | Create htpasswd | check if htpasswd exists
  stat:
    path: "/opt/nginx-proxy/htpasswd/{{ lookup('vars', role_name + '_subdomain') }}.{{ user.domain }}"
  register: htpasswd_status

- name: Resources | Tasks | Nginx-Proxy | Create htpasswd | create htpasswd when it doesn't already exist
  htpasswd:
    path: "/opt/nginx-proxy/htpasswd/{{ lookup('vars', role_name + '_subdomain') }}.{{ user.domain }}"
    name: "{{ user.name }}"
    password: "{{ user.pass }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0664
    state: present
    create: yes
  when: htpasswd_status.stat.exists
