##########################################################################
# Title:         Cloudbox: Emby | Default Variables                      #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Name
################################

emby_name: emby

################################
# Subdomain
################################

emby_subdomain: "{{ emby_name }}"

subdomain: "{{ emby_subdomain }}"

################################
# Folders
################################

emby_folder: "{{ emby_name }}"

app_folder: "{{ emby_folder }}"

emby_transcodes_path: "{{ plex.transcodes }}/{{ app_folder }}"

emby_folders:
  - "{{ server_appdata_path }}/{{ app_folder }}"
  - "{{ server_appdata_path }}/{{ app_folder }}/config"
  - "{{ server_appdata_path }}/{{ app_folder }}/config/users"
  - "{{ emby_transcodes_path }}"

folders: "{{ emby_folders }}"

################################
# Files
################################

emby_config_file_path: "{{ server_appdata_path }}/{{ app_folder }}/config/system.xml"

emby_dlna_file_path: "{{ server_appdata_path }}/{{ app_folder }}/config/dlna.xml"

################################
# Docker Container
################################

emby_docker_name: "{{ emby_name }}"

docker_name: "{{ emby_docker_name }}"

################################
# Docker Image
################################

emby_docker_image: "emby/embyserver:{{ emby.version }}"

docker_image: "{{ emby_docker_image }}"

emby_docker_pull: yes

docker_pull: "{{ emby_docker_pull }}"

################################
# Docker Ports
################################

emby_docker_ports:
  - "8096:8096"

docker_ports: "{{ emby_docker_ports
                  if (not reverse_proxy_is_enabled)
                  else [] }}"

################################
# Docker Envs
################################

emby_port: 8096

web_port: "{{ emby_port }}"

emby_docker_envs_standard:
  UID: "{{ uid }}"
  GID: "{{ gid }}"
  GIDLIST: "{{ vgid }}"
  NVIDIA_DRIVER_CAPABILITIES: "{{ 'compute,video,utility' if (gpu.nvidia.enabled) | default(false) else omit }}"
  NVIDIA_VISIBLE_DEVICES: "{{ 'all' if (gpu.nvidia.enabled) | default(false) else omit }}"
  TZ: "{{ tz }}"

emby_docker_envs_reverse_proxy_extras:
  HTTPS_METHOD: noredirect

emby_docker_envs: "{{ (emby_docker_envs_standard |
                          combine(docker_envs_reverse_proxy) |
                          combine(emby_docker_envs_reverse_proxy_extras))
                      if (reverse_proxy_is_enabled)
                      else (emby_docker_envs_standard) }}"

docker_envs: "{{ emby_docker_envs }}"

################################
# Docker Volumes
################################

emby_docker_volumes:
  - "{{ server_appdata_path }}/{{ app_folder }}:/config"
  - "{{ server_appdata_path }}/scripts:/scripts"
  - "/mnt/unionfs/Media:/data"
  - "/mnt:/mnt"
  - "/tmp:/tmp"
  - "/dev/shm:/dev/shm"
  - "{{ emby_transcodes_path }}:/transcode"

docker_volumes: "{{ emby_docker_volumes }}"

################################
# Docker Devices
################################

emby_docker_devices: []

docker_devices: "{{ emby_docker_devices }}"

################################
# Docker Hosts
################################

emby_docker_hosts_default: []

emby_docker_hosts_custom: []

emby_docker_hosts: "{{ emby_docker_hosts_default | combine(emby_docker_hosts_custom) }}"

docker_hosts: "{{ emby_docker_hosts }}"

################################
# Docker Labels
################################

emby_docker_labels:
    - '{ "traefik.http.services.{{ subdomain }}.loadbalancer.server.port": "{{ web_port }}" }'

docker_labels: "{{ docker_labels_common | combine(emby_docker_labels) }}"

################################
# Docker Networks
################################

emby_docker_network_alias: "{{ emby_name }}"

docker_network_alias: "{{ emby_docker_network_alias }}"

emby_docker_networks: []

docker_networks: "{{ (docker_networks_common)
                      if not (emby_docker_networks and
                              emby_docker_networks | length > 0)
                      else (emby_docker_networks) }}"

################################
# Docker Capabilities
################################

emby_docker_capabilities: []

docker_capabilities: "{{ emby_docker_capabilities }}"

################################
# Docker Security
################################

emby_docker_security_opts: []

docker_security_opts: "{{ emby_docker_security_opts }}"

################################
# Docker Restart Policy
################################

emby_docker_restart_policy: unless-stopped

docker_restart_policy: "{{ emby_docker_restart_policy }}"

################################
# Docker State
################################

emby_docker_state: started

docker_state: "{{ emby_docker_state }}"
