##########################################################################
# Title:         Cloudbox: Emby | Default Variables                      #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Name
################################

emby_name: emby

################################
# Subdomain
################################

emby_subdomain: "{{ emby_name }}"

################################
# Folders
################################

emby_folder: "{{ emby_name }}"

emby_transcodes_path: "{{ transcodes_path }}/{{ emby_folder }}"

emby_path: "{{ server_appdata_path }}/{{ emby_folder }}"

emby_folders:
  - "{{ emby_path }}"
  - "{{ emby_path }}/config"
  - "{{ emby_path }}/config/users"
  - "{{ emby_transcodes_path }}"

################################
# Files
################################

emby_config_file_path: "{{ emby_path }}/config/system.xml"

emby_dlna_file_path: "{{ emby_path }}/config/dlna.xml"

################################
# Settings
################################

emby_config_settings:
  # set 'IsBehindProxy' to 'true'
  - { xpath: 'IsBehindProxy', value: 'true' }
  # set 'WanDdns' to 'emby.{{ user.domain }}'
  - { xpath: 'WanDdns', value: 'emby.{{ user.domain }}' }
  # set 'PublicPort' to '80'
  - { xpath: 'PublicPort', value: '80' }
  # set 'PublicHttpsPort' to '443'
  - { xpath: 'PublicHttpsPort', value: '443' }
  # set 'EnableHttps' to 'true'
  - { xpath: 'EnableHttps', value: 'true' }
  # set 'RequireHttps' to 'false'
  - { xpath: 'RequireHttps', value: 'false' }
  # set 'EnableUPnP' to 'false'
  - { xpath: 'EnableUPnP', value: 'false' }
  # set 'EnableAnonymousUsageReporting' to 'false'
  - { xpath: 'EnableAnonymousUsageReporting', value: 'false' }

################################
# Docker Container
################################

emby_docker_container: "{{ emby_name }}"

################################
# Docker Image
################################

emby_docker_image: "emby/embyserver:{{ emby.version }}"

emby_docker_pull: yes

################################
# Docker Ports
################################

emby_ports:
  - "8096:8096"

emby_docker_ports: "{{ emby_ports
                       if (not reverse_proxy_is_enabled)
                       else [] }}"

################################
# Docker Envs
################################

emby_web_port: 8096

emby_docker_envs_standard:
  UID: "{{ uid }}"
  GID: "{{ gid }}"
  GIDLIST: "{{ vgid }}"
  NVIDIA_DRIVER_CAPABILITIES: "{{ 'compute,video,utility' if (gpu.nvidia.enabled) | default(false) else omit }}"
  NVIDIA_VISIBLE_DEVICES: "{{ 'all' if (gpu.nvidia.enabled) | default(false) else omit }}"
  TZ: "{{ tz }}"

emby_docker_envs_reverse_proxy_extras:
  HTTPS_METHOD: noredirect

emby_docker_envs: "{{ (emby_docker_envs_standard |
                          combine(docker_envs_reverse_proxy) |
                          combine(emby_docker_envs_reverse_proxy_extras))
                      if (reverse_proxy_is_enabled)
                      else (emby_docker_envs_standard) }}"

################################
# Docker Volumes
################################

emby_docker_volumes:
  - "{{ emby_path }}:/config"
  - "{{ server_appdata_path }}/scripts:/scripts"
  - "/mnt/unionfs/Media:/data"
  - "/mnt:/mnt"
  - "/tmp:/tmp"
  - "/dev/shm:/dev/shm"
  - "{{ emby_transcodes_path }}:/transcode"

################################
# Docker Devices
################################

emby_docker_devices: []

################################
# Docker Hosts
################################

emby_docker_hosts_custom: []

emby_docker_hosts: "{{ docker_hosts_common | combine(plex_docker_hosts_custom) }}"

################################
# Docker Labels
################################

emby_docker_labels:
    - '{ "traefik.http.services.{{ subdomain }}.loadbalancer.server.port": "{{ web_port }}" }'
    - "traefik.enable": "true"

emby_docker_labels: "{{ docker_labels_common | combine(emby_docker_labels_custom) }}"

################################
# Docker Hostname
################################

emby_docker_hostname: "{{ emby_name }}"

################################
# Docker Networks
################################

emby_docker_networks_alias: "{{ emby_name }}"

emby_docker_networks_custom: []

emby_docker_networks: "{{ docker_networks_common + emby_docker_networks_custom }}"

################################
# Docker Capabilities
################################

emby_docker_capabilities: []

################################
# Docker Security
################################

emby_docker_security_opts: []

################################
# Docker Restart Policy
################################

emby_docker_restart_policy: unless-stopped

################################
# Docker State
################################

emby_docker_state: started
