##########################################################################
# Title:         Cloudbox: Jackett | Default Variables                   #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Name
################################

jackett_name: jackett

################################
# Subdomain
################################

jackett_subdomain: "{{ jackett_name }}"

################################
# Folders
################################

jackett_folder: "{{ jackett_name }}"

jackett_path: "{{ server_appdata_path }}/{{ jackett_folder }}"

jackett_folders:
  - "{{ jackett_path }}"

################################
# Files
################################


################################
# Docker Container
################################

jackett_docker_container: "{{ jackett_name }}"

################################
# Docker Image
################################

jackett_docker_image: "hotio/jackett:unstable"

jackett_docker_pull: yes

################################
# Docker Ports
################################

jackett_ports:
  - "9117:9117"

jackett_docker_ports: "{{ jackett_ports
                          if (not reverse_proxy_is_enabled)
                          else [] }}"

################################
# Docker Envs
################################

jackett_web_port: 9117

jackett_docker_envs_standard:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  UMASK: "002"
  TZ: "{{ tz }}"

jackett_docker_envs_reverse_proxy_extras: {}

jackett_docker_envs: "{{ (jackett_docker_envs_standard |
                              combine(docker_envs_reverse_proxy) |
                              combine(jackett_docker_envs_reverse_proxy_extras))
                          if (reverse_proxy_is_enabled)
                          else (jackett_docker_envs_standard) }}"

################################
# Docker Volumes
################################

jackett_docker_volumes:
  - "{{ jackett_path }}:/config"
  - "/mnt:/mnt"

################################
# Docker Devices
################################

jackett_docker_devices: []

################################
# Docker Hosts
################################

jackett_docker_hosts_custom: []

jackett_docker_hosts: "{{ docker_hosts_common | combine(jackett_docker_hosts_custom) }}"

################################
# Docker Labels
################################

jackett_docker_labels:
    - '{ "traefik.http.services.{{ subdomain }}.loadbalancer.server.port": "{{ web_port }}" }'
    - "traefik.enable": "true"

jackett_docker_labels: "{{ docker_labels_common | combine(jackett_docker_labels_custom) }}"

################################
# Docker Hostname
################################

jackett_docker_hostname: "{{ jackett_name }}"

################################
# Docker Networks
################################

jackett_docker_networks_alias: "{{ jackett_name }}"

jackett_docker_networks_custom: []

jackett_docker_networks: "{{ docker_networks_common + jackett_docker_networks_custom }}"

################################
# Docker Capabilities
################################

jackett_docker_capabilities: []

################################
# Docker Security
################################

jackett_docker_security_opts: []

################################
# Docker Restart Policy
################################

jackett_docker_restart_policy: unless-stopped

################################
# Docker State
################################

jackett_docker_state: started
