#########################################################################
# Title:         Cloudbox: Emby | Settings Task                         #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Post-Install | Wait for config file to be created
  wait_for:
    path: "{{ emby_config_file_path }}"
    state: present

- name: Settings | Stop Docker container
  docker_container:
    name: "{{ emby_docker_container }}"
    state: stopped

- name: Settings | Update config file
  xml:
    path: "{{ emby_config_file_path }}"
    xpath: "/ServerConfiguration/{{ item.xpath }}"
    value: "{{ item.value }}"
  become: yes
  become_user: "{{ user.name }}"
  loop: "{{ emby_config_settings }}"

- name: Settings | Start Docker container
  docker_container:
    name: "{{ emby_docker_container }}"
    state: "{{ emby_docker_state }}"
