#########################################################################
# Title:         Cloudbox: Tautulli Role                                #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Migration Tasks
  include_tasks: "subtasks/legacy_migration.yml"
  when: lookup('vars', role_name + '_path') != server_appdata_path + '/plexpy'

- name: Create DNS Record
  include_role:
    name: dns
  vars:
    record: "{{ item }}"
  loop:
    - "{{ lookup('vars', role_name + '_subdomain') }}"

- name: Remove existing Docker container
  docker_container:
    name: "{{ lookup('vars', role_name + '_docker_container') }}"
    state: absent

- name: Wait for Plex Logs folder to be created by Plex
  wait_for:
    path: "{{ plex_log_path }}"
    state: present
  when: (not continuous_integration)

- name: Create directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items: "{{ lookup('vars', role_name + '_folders') }}"

- name: Create Docker container
  include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
