#########################################################################
# Title:         Cloudbox: SABnzbd | Settings Tasks                     #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Wait for config file to be created
  wait_for:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    state: present

- name: Stop container
  docker_container:
    name: sabnzbd
    state: stopped

- name: "Wait for 10 seconds"
  wait_for:
    timeout: 10

- name: Update config
  ini_file:
    path: "/opt/sabnzbd/app/sabnzbd.ini"
    section: misc
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
  loop:
    # host whitelist
    - { option: "host_whitelist", value: "sabnzbd.{{ user.domain }}" }
    # url base (null)
    - { option: "url_base", value: "" }
    # form auth (off)
    - { option: "html_login", value: "1" }
    # username
    - { option: "username", value: "{{ user.name }}" }
    # password
    - { option: "password", value: "{{ user.pass }}" }
    # watch directory
    - { option: "dirscan_dir", value: "/downloads/nzbs/sabnzbd/watch" }
    # incomplete downloads directory
    - { option: "download_dir", value: "/downloads/nzbs/sabnzbd/incomplete" }
    # complete downloads directory
    - { option: "complete_dir", value: "/downloads/nzbs/sabnzbd/complete" }
    # logs directory
    - { option: "log_dir", value: "/downloads/nzbs/sabnzbd/logs'" }
    # script directory
    - { option: "script_dir", value: "/scripts'" }

- name: Start container
  docker_container:
    name: sabnzbd
    state: started
