#########################################################################
# Title:         Cloudbox: Nginx-Proxy | CF-Real-IP Tasks               #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: CF-Real-IP | Stop and remove any existing container
  docker_container:
    name: cfrealip
    state: absent
    container_default_behavior: compatibility

- name: CF-Real-IP | Create and start container
  docker_container:
    name: cfrealip
    image: "mikenowak/nginx-cf-real-ip"
    pull: yes
    volumes_from:
      - "nginx-proxy"
    env:
      TZ: "{{ tz }}"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - cfrealip
    networks_cli_compatible: yes
    network_mode: "{{ docker_networks_name_common }}"
    purge_networks: yes
    container_default_behavior: compatibility
    restart_policy: unless-stopped
    state: started

- name: CF-Real-IP | Restart 'nginx-proxy' container
  docker_container:
    name: nginx-proxy
    restart: yes
