##########################################################################
# Title:         Cloudbox: MariaDB | Default Variables                   #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Name
################################

mariadb_name: mariadb

################################
# Subdomain
################################


################################
# Folders
################################

mariadb_folder: "{{ mariadb_name }}"

mariadb_path: "{{ server_appdata_path }}/{{ mariadb_folder }}"

mariadb_folders:
  - "{{ mariadb_path }}"

################################
# Files
################################


################################
# Docker Container
################################

mariadb_docker_container: "{{ mariadb_name }}"

################################
# Docker Image
################################

mariadb_docker_image: "linuxserver/mariadb"

mariadb_docker_pull: yes

################################
# Docker Ports
################################

mariadb_docker_ports: []

################################
# Docker Envs
################################

mariadb_mysql_root_password: password321

mariadb_docker_envs:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  MYSQL_ROOT_PASSWORD: "{{ mariadb_mysql_root_password }}"

################################
# Docker Volumes
################################

mariadb_docker_volumes:
  - "{{ mariadb_path }}:/config"

################################
# Docker Devices
################################

mariadb_docker_devices: []

################################
# Docker Hosts
################################

mariadb_docker_hosts_custom: []

mariadb_docker_hosts: "{{ docker_hosts_common | combine(mariadb_docker_hosts_custom) }}"

################################
# Docker Labels
################################

mariadb_docker_labels:
    - '{ "traefik.http.services.{{ subdomain }}.loadbalancer.server.port": "{{ web_port }}" }'
    - "traefik.enable": "false"

mariadb_docker_labels: "{{ docker_labels_common | combine(mariadb_docker_labels_custom) }}"

################################
# Docker Hostname
################################

mariadb_docker_hostname: "{{ mariadb_name }}"

################################
# Docker Networks
################################

mariadb_docker_networks_alias: "{{ mariadb_name }}"

mariadb_docker_networks_custom: []

mariadb_docker_networks: "{{ docker_networks_common + mariadb_docker_networks_custom }}"

################################
# Docker Capabilities
################################

mariadb_docker_capabilities: []

################################
# Docker Security
################################

mariadb_docker_security_opts: []

################################
# Docker Restart Policy
################################

mariadb_docker_restart_policy: unless-stopped

################################
# Docker State
################################

mariadb_docker_state: started
