##########################################################################
# Title:         Cloudbox: MariaDB | Default Variables                   #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Name
################################

mariadb_name: mariadb

################################
# Subdomain
################################


################################
# Folders
################################

mariadb_folder: "{{ mariadb_name }}"

app_folder: "{{ mariadb_folder }}"

mariadb_folders:
  - "{{ server_appdata_path }}/{{ app_folder }}"

folders: "{{ mariadb_folders }}"

################################
# Files
################################


################################
# Docker Container
################################

mariadb_docker_name: "{{ mariadb_name }}"

docker_name: "{{ mariadb_docker_name }}"

################################
# Docker Image
################################

mariadb_docker_image: "linuxserver/mariadb"

docker_image: "{{ mariadb_docker_image }}"

mariadb_docker_pull: yes

docker_pull: "{{ mariadb_docker_pull }}"

################################
# Docker Ports
################################

mariadb_docker_ports: []

docker_ports: "{{ mariadb_docker_ports
                  if (not reverse_proxy_is_enabled)
                  else [] }}"

################################
# Docker Envs
################################

mariadb_port: 3306

web_port: "{{ mariadb_port }}"

mariadb_mysql_root_password: password321

mariadb_docker_envs_standard:
  PUID: "{{ uid }}"
  PGID: "{{ gid }}"
  TZ: "{{ tz }}"
  MYSQL_ROOT_PASSWORD: "{{ mariadb_mysql_root_password }}"

mariadb_docker_envs_reverse_proxy_extras: {}

mariadb_docker_envs: "{{ mariadb_docker_envs_standard }}"

docker_envs: "{{ mariadb_docker_envs }}"

################################
# Docker Volumes
################################

mariadb_docker_volumes:
  - "{{ server_appdata_path }}/{{ app_folder }}:/config"

docker_volumes: "{{ mariadb_docker_volumes }}"

################################
# Docker Devices
################################

mariadb_docker_devices: []

docker_devices: "{{ mariadb_docker_devices }}"

################################
# Docker Hosts
################################

mariadb_docker_hosts_default: []

mariadb_docker_hosts_custom: []

mariadb_docker_hosts: "{{ mariadb_docker_hosts_default | combine(mariadb_docker_hosts_custom) }}"

docker_hosts: "{{ mariadb_docker_hosts }}"

################################
# Docker Labels
################################

mariadb_docker_labels:
    - '{ "traefik.http.services.{{ subdomain }}.loadbalancer.server.port": "{{ web_port }}" }'
    - "traefik.enable": "false"

docker_labels: "{{ docker_labels_common | combine(mariadb_docker_labels) }}"

################################
# Docker Networks
################################

mariadb_docker_network_alias: "{{ mariadb_name }}"

docker_network_alias: "{{ mariadb_docker_network_alias }}"

mariadb_docker_networks: []

docker_networks: "{{ (docker_networks_common)
                      if not (mariadb_docker_networks and
                              mariadb_docker_networks | length > 0)
                      else (mariadb_docker_networks) }}"

################################
# Docker Capabilities
################################

mariadb_docker_capabilities: []

docker_capabilities: "{{ mariadb_docker_capabilities }}"

################################
# Docker Security
################################

mariadb_docker_security_opts: []

docker_security_opts: "{{ mariadb_docker_security_opts }}"

################################
# Docker Restart Policy
################################

mariadb_docker_restart_policy: unless-stopped

docker_restart_policy: "{{ mariadb_docker_restart_policy }}"

################################
# Docker State
################################

mariadb_docker_state: started

docker_state: "{{ mariadb_docker_state }}"
