#########################################################################
# Title:         Cloudbox: DNS | Cloudflare | Create DNS Record         #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Cloudflare | Install 'dnsutils'
  apt: "name=dnsutils state=present"

- name: Cloudflare | Get Public IP Address
  shell: "{{ ip_address_lookup_command }}"
  register: public_ip_lookup

- name: Cloudflare | Set 'public_ip' variable
  set_fact:
    public_ip: "{{ public_ip_lookup.stdout }}"

- name: Cloudflare | Set DNS Record
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    zone: "{{ user.domain }}"
    state: present
    solo: true
    proxied: no
    type: A
    value: "{{ public_ip }}"
    record: "{{ record }}"
  register: cloudflare_dns_record_creation_status

- name: Cloudflare | Tasks on success
  block:

  - name: Cloudflare | Set 'record_temp' variable
    set_fact:
      record_temp: "{{ (record == user.domain) | ternary(user.domain,record + '.' + user.domain) }}"

  - name: Cloudflare | Display DNS record creation status
    debug:
      msg: "DNS Record for '{{ record_temp }}' set to '{{ public_ip }}'."

  when: cloudflare_dns_record_creation_status is succeeded
