#########################################################################
# Title:         Cloudbox: DNS | Cloudflare | Remove DNS Record         #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Cloudflare | Remove DNS Record
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    zone: "{{ user.domain }}"
    state: absent
    type: A
    record: "{{ record }}"
  register: cloudflare_dns_record_removal_status

- name: Cloudflare | Tasks on success
  block:

  - name: Cloudflare | Set 'record_temp' variable
    set_fact:
      record_temp: "{{ (record == user.domain) | ternary(user.domain,record + '.' + user.domain) }}"

  - name: Cloudflare | Display DNS record removal status
    debug:
      msg: "DNS Record for '{{ record_temp }}' was removed."

  when: cloudflare_dns_record_removal_status is succeeded
