##########################################################################
# Title:         Cloudbox: Netdata | Default Variables                   #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Name
################################

netdata_name: netdata

################################
# Subdomain
################################

netdata_subdomain: "{{ netdata_name }}"

################################
# Folders
################################

netdata_folder: "{{ netdata_name }}"

netdata_path: "{{ server_appdata_path }}/{{ netdata_folder }}"

netdata_folders:
  - "{{ netdata_path }}"

################################
# Files
################################

netdata_config_override: "{{ netdata_path }}/override"

################################
# Docker Container
################################

netdata_docker_container: "{{ netdata_name }}"

################################
# Docker Image
################################

netdata_docker_image: "titpetric/netdata:latest"

netdata_docker_pull: yes

################################
# Docker Ports
################################

netdata_ports:
  - "19999:19999"

netdata_docker_ports: "{{ netdata_ports
                          if (not reverse_proxy_is_enabled)
                          else [] }}"

################################
# Docker Envs
################################

netdata_web_port: 19999

netdata_docker_envs_standard:
  TZ: "{{ tz }}"

netdata_docker_envs_reverse_proxy_extras: {}

netdata_docker_envs: "{{ (netdata_docker_envs_standard |
                              combine(docker_envs_reverse_proxy) |
                              combine(netdata_docker_envs_reverse_proxy_extras))
                          if (reverse_proxy_is_enabled)
                          else (netdata_docker_envs_standard) }}"

################################
# Docker Volumes
################################

netdata_docker_volumes:
  - "{{ netdata_path }}:/config"
  - "/proc:/host/proc:ro"
  - "/sys:/host/sys:ro"
  - "/var/run/docker.sock:/var/run/docker.sock"

netdata_docker_volumes_config_override:
  - "{{ netdata_config_override }}:/etc/netdata/override:ro"

################################
# Docker Devices
################################

netdata_docker_devices: []

################################
# Docker Hosts
################################

netdata_docker_hosts_custom: []

netdata_docker_hosts: "{{ docker_hosts_common | combine(netdata_docker_hosts_custom) }}"

################################
# Docker Labels
################################

netdata_docker_labels:
    - '{ "traefik.http.services.{{ subdomain }}.loadbalancer.server.port": "{{ web_port }}" }'
    - '{ "traefik.http.routers.{{ subdomain }}.middlewares": "authtraefik" }'
    - traefik.http.middlewares.authtraefik.basicauth.usersfile: "/etc/traefik/.htpasswd"
    - "traefik.enable": "true"


docker_labels: "{{ docker_labels_common | combine(netdata_docker_labels) }}"

################################
# Docker Hostname
################################

netdata_docker_hostname: "{{ netdata_name }}"

################################
# Docker Networks
################################

netdata_docker_networks_alias: "{{ netdata_name }}"

netdata_docker_networks_custom: []

netdata_docker_networks: "{{ docker_networks_common + netdata_docker_networks_custom }}"

################################
# Docker Capabilities
################################

netdata_docker_capabilities:
  - SYS_PTRACE

################################
# Docker Security
################################

netdata_docker_security_opts:
  - apparmor:unconfined

################################
# Docker Restart Policy
################################

netdata_docker_restart_policy: unless-stopped

################################
# Docker State
################################

netdata_docker_state: started
