##########################################################################
# Title:         Cloudbox: Plex Plugins / WebTools | Default Variables   #
# Author(s):     desimaniac                                              #
# URL:           https://github.com/cloudbox/cloudbox                    #
# --                                                                     #
#         Part of the Cloudbox project: https://cloudbox.works           #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Paths
################################

plex_plugin_webtools_path: "{{ plex_plugins_path }}/WebTools.bundle"

plex_plugin_webtools_version_path: "{{ plex_plugin_webtools_path }}/VERSION"

plex_plugin_webtools_preferences_path: "{{ plex_plugin_support_path }}/Preferences/com.plexapp.plugins.WebTools.xml"

################################
# Repository
################################

plex_plugin_webtools_release_url: https://api.github.com/repos/ukdtom/WebTools.bundle/releases/latest

plex_plugin_webtools_download_url_backup: https://github.com/ukdtom/WebTools.bundle/releases/download/3.0.0/WebTools.bundle.zip
